import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";
import Nav from "../components/Nav";
import requests from "../utils/requests";
import Contents from "../components/Contents";

export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/*Header*/}
        <Header/>
        {/*Nav*/}
        <Nav/>
        {/*Contents*/}
        <Contents results={results}/>
    </div>
  )
}
;

export async function getServerSideProps(context){
    const genre = context.query.genre;

    const request = await fetch(
        `https://api.themoviedb.org/3${
            requests[genre]?.url || requests.fetchTrending.url
        }`
    );
    const data = await request.json();

    return {
        props:{
            results: data.results,
        },
    }
}
